services:
    acme.demo.controller:
        class: acme\demo\controller\main
        arguments:
            - @dbal.conn
            - @user
            - @config
            - @controller.helper
            - @template
    acme.demo.listener:
        class: acme\demo\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
